export const blogsData=[
   { id : 1,
    title :"html",
    body:"Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit."
   },
   { id : 2,
    title :"php",
    body:"Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit."
   },
   { id : 3,
    title :"react",
    body:"Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit."
   },
   { id : 4,
    title :"vue",
    body:"Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit."
   },
   { id : 5,
    title :"laravel",
    body:"Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit.Voluptate incididunt elit aliqua veniam excepteur cillum proident. Duis reprehenderit labore magna magna et deserunt ea est. Ut eu aliquip pariatur duis in ea. Dolore sit sit deserunt sit commodo. Enim adipisicing ad sit enim velit consequat. Pariatur quis minim consectetur laboris ullamco mollit."
   }
]